server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ljm_project
    password: dlwjdans1@
    url: jdbc:mysql://localhost:3306/ljm_project?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
  # View Resolver 설정 - JSP 적용때문에
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
### MYBATIS ###
mybatis:
  mapper-locations: mybatis/mapper/**/**.xml

