server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ljm_project
    password: dlwjdans1@
    url: jdbc:mysql://localhost:3306/learn?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

### MYBATIS ###
mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"